language: java

before_install:
  - chmod +x mvnw

cache:
  directories:
    - $HOME/.m2

addons:
  sonarcloud:
    organization: "cs-jms"
    token:
      secure: $SONAR_TOKEN

jobs:
  include:
    - stage: build
      name: "Build"
      script: ./mvnw clean compile
    - stage: test
      name: "Test"
      script: ./mvnw jacoco:prepare-agent verify -Pci-sonar -Dsonar.projectKey=CaseStudy-JobManagement_jm-service  -Dsonar.host.url=https://sonarcloud.io
    - stage: deploy
      name: "Deploy"
      deploy:
        provider: heroku
        api-key:
          secure: $HEROKU_TOKEN
        app: jm-service