language: java

before_install:
  - chmod +x mvnw

cache:
  directories:
    - $HOME/.m2

addons:
  sonarcloud:
    organization: "cs-jms"
    token:
      secure: $SONAR_TOKEN

jobs:
  include:
    - stage: build
      name: "Build"
      script: ./mvnw clean compile
    - stage: test
      name: "Test"
      script: ./mvnw jacoco:prepare-agent test -Pci -Dsonar.projectKey=CaseStudy-JobManagement_jm-service  -Dsonar.host.url=https://sonarcloud.io