spring:
  profiles:
    active: "dev"
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  activemq:
    in-memory: true
    pool:
      enable: false

server:
  servlet:
    contextPath: /api

---

spring:
  profiles: dev
app:
  fileStore: ".store"
  db:
    name: job
    host: localhost
    port: 27107

---

spring:
  profiles: prod
app:
  fileStore: ".store"
  db:
    name: job
#    host: {ip}
#    port: {port}