spring:
  profiles:
    active: "dev"
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server:
  servlet:
    contextPath: /api
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
---

spring:
  profiles: dev
app:
  jobStore: ".store"
  db:
    name: job
    host: localhost
    port: 27107

---

spring:
  profiles: prod
app:
  jobStore: ".store"
  db:
    name: job
#    host: {ip}
#    port: {port}