spring:
  profiles:
    active: "dev"

server:
  servlet:
    contextPath: /api

---

spring:
  profiles: dev
app:
  jobStore: ".store"
  db:
    name: job
    host: localhost
    port: 27107

---

spring:
  profiles: prod
app:
  jobStore: ".store"
  db:
    name: job
#    host: {ip}
#    port: {port}